server:
  port: 8081
  

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      accessKey: A*******************WH
      secretkey: S*****************************************J
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/138878554440/spring-boot-sqs